2014-02-10 18:42:46,869 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'com.nest5.Nest5Client.Member' on field 'address': rejected value [null]; codes [com.nest5.Nest5Client.Member.address.nullable.error.com.nest5.Nest5Client.Member.address,com.nest5.Nest5Client.Member.address.nullable.error.address,com.nest5.Nest5Client.Member.address.nullable.error.java.lang.String,com.nest5.Nest5Client.Member.address.nullable.error,member.address.nullable.error.com.nest5.Nest5Client.Member.address,member.address.nullable.error.address,member.address.nullable.error.java.lang.String,member.address.nullable.error,com.nest5.Nest5Client.Member.address.nullable.com.nest5.Nest5Client.Member.address,com.nest5.Nest5Client.Member.address.nullable.address,com.nest5.Nest5Client.Member.address.nullable.java.lang.String,com.nest5.Nest5Client.Member.address.nullable,member.address.nullable.com.nest5.Nest5Client.Member.address,member.address.nullable.address,member.address.nullable.java.lang.String,member.address.nullable,nullable.com.nest5.Nest5Client.Member.address,nullable.address,nullable.java.lang.String,nullable]; arguments [address,class com.nest5.Nest5Client.Member]; default message [La propiedad [{0}] no puede ser nula]

	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractSavePersistentMethod.doInvokeInternal(AbstractSavePersistentMethod.java:190)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractDynamicPersistentMethod.invoke(AbstractDynamicPersistentMethod.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1243)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at org.codehaus.groovy.grails.orm.hibernate.HibernateGormInstanceApi.save(HibernateGormEnhancer.groovy:911)
	at com.nest5.Nest5Client.Member.save(Member.groovy)
	at com.nest5.Nest5Client.Member$save.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at BootStrap$_closure1.doCall(BootStrap.groovy:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1243)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:950)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
	at groovy.lang.Closure.call(Closure.java:415)
	at groovy.lang.Closure.call(Closure.java:409)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:74)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:108)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4791)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5285)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-10 18:42:46,871 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'com.nest5.Nest5Client.Member' on field 'address': rejected value [null]; codes [com.nest5.Nest5Client.Member.address.nullable.error.com.nest5.Nest5Client.Member.address,com.nest5.Nest5Client.Member.address.nullable.error.address,com.nest5.Nest5Client.Member.address.nullable.error.java.lang.String,com.nest5.Nest5Client.Member.address.nullable.error,member.address.nullable.error.com.nest5.Nest5Client.Member.address,member.address.nullable.error.address,member.address.nullable.error.java.lang.String,member.address.nullable.error,com.nest5.Nest5Client.Member.address.nullable.com.nest5.Nest5Client.Member.address,com.nest5.Nest5Client.Member.address.nullable.address,com.nest5.Nest5Client.Member.address.nullable.java.lang.String,com.nest5.Nest5Client.Member.address.nullable,member.address.nullable.com.nest5.Nest5Client.Member.address,member.address.nullable.address,member.address.nullable.java.lang.String,member.address.nullable,nullable.com.nest5.Nest5Client.Member.address,nullable.address,nullable.java.lang.String,nullable]; arguments [address,class com.nest5.Nest5Client.Member]; default message [La propiedad [{0}] no puede ser nula]

	at BootStrap$_closure1.doCall(BootStrap.groovy:41)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-10 18:42:46,871 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'com.nest5.Nest5Client.Member' on field 'address': rejected value [null]; codes [com.nest5.Nest5Client.Member.address.nullable.error.com.nest5.Nest5Client.Member.address,com.nest5.Nest5Client.Member.address.nullable.error.address,com.nest5.Nest5Client.Member.address.nullable.error.java.lang.String,com.nest5.Nest5Client.Member.address.nullable.error,member.address.nullable.error.com.nest5.Nest5Client.Member.address,member.address.nullable.error.address,member.address.nullable.error.java.lang.String,member.address.nullable.error,com.nest5.Nest5Client.Member.address.nullable.com.nest5.Nest5Client.Member.address,com.nest5.Nest5Client.Member.address.nullable.address,com.nest5.Nest5Client.Member.address.nullable.java.lang.String,com.nest5.Nest5Client.Member.address.nullable,member.address.nullable.com.nest5.Nest5Client.Member.address,member.address.nullable.address,member.address.nullable.java.lang.String,member.address.nullable,nullable.com.nest5.Nest5Client.Member.address,nullable.address,nullable.java.lang.String,nullable]; arguments [address,class com.nest5.Nest5Client.Member]; default message [La propiedad [{0}] no puede ser nula]

	at BootStrap$_closure1.doCall(BootStrap.groovy:41)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-10 18:42:46,871 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'com.nest5.Nest5Client.Member' on field 'address': rejected value [null]; codes [com.nest5.Nest5Client.Member.address.nullable.error.com.nest5.Nest5Client.Member.address,com.nest5.Nest5Client.Member.address.nullable.error.address,com.nest5.Nest5Client.Member.address.nullable.error.java.lang.String,com.nest5.Nest5Client.Member.address.nullable.error,member.address.nullable.error.com.nest5.Nest5Client.Member.address,member.address.nullable.error.address,member.address.nullable.error.java.lang.String,member.address.nullable.error,com.nest5.Nest5Client.Member.address.nullable.com.nest5.Nest5Client.Member.address,com.nest5.Nest5Client.Member.address.nullable.address,com.nest5.Nest5Client.Member.address.nullable.java.lang.String,com.nest5.Nest5Client.Member.address.nullable,member.address.nullable.com.nest5.Nest5Client.Member.address,member.address.nullable.address,member.address.nullable.java.lang.String,member.address.nullable,nullable.com.nest5.Nest5Client.Member.address,nullable.address,nullable.java.lang.String,nullable]; arguments [address,class com.nest5.Nest5Client.Member]; default message [La propiedad [{0}] no puede ser nula]

	at BootStrap$_closure1.doCall(BootStrap.groovy:41)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-10 18:42:46,872 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'com.nest5.Nest5Client.Member' on field 'address': rejected value [null]; codes [com.nest5.Nest5Client.Member.address.nullable.error.com.nest5.Nest5Client.Member.address,com.nest5.Nest5Client.Member.address.nullable.error.address,com.nest5.Nest5Client.Member.address.nullable.error.java.lang.String,com.nest5.Nest5Client.Member.address.nullable.error,member.address.nullable.error.com.nest5.Nest5Client.Member.address,member.address.nullable.error.address,member.address.nullable.error.java.lang.String,member.address.nullable.error,com.nest5.Nest5Client.Member.address.nullable.com.nest5.Nest5Client.Member.address,com.nest5.Nest5Client.Member.address.nullable.address,com.nest5.Nest5Client.Member.address.nullable.java.lang.String,com.nest5.Nest5Client.Member.address.nullable,member.address.nullable.com.nest5.Nest5Client.Member.address,member.address.nullable.address,member.address.nullable.java.lang.String,member.address.nullable,nullable.com.nest5.Nest5Client.Member.address,nullable.address,nullable.java.lang.String,nullable]; arguments [address,class com.nest5.Nest5Client.Member]; default message [La propiedad [{0}] no puede ser nula]

	at BootStrap$_closure1.doCall(BootStrap.groovy:41)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
2014-02-10 18:42:46,872 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'com.nest5.Nest5Client.Member' on field 'address': rejected value [null]; codes [com.nest5.Nest5Client.Member.address.nullable.error.com.nest5.Nest5Client.Member.address,com.nest5.Nest5Client.Member.address.nullable.error.address,com.nest5.Nest5Client.Member.address.nullable.error.java.lang.String,com.nest5.Nest5Client.Member.address.nullable.error,member.address.nullable.error.com.nest5.Nest5Client.Member.address,member.address.nullable.error.address,member.address.nullable.error.java.lang.String,member.address.nullable.error,com.nest5.Nest5Client.Member.address.nullable.com.nest5.Nest5Client.Member.address,com.nest5.Nest5Client.Member.address.nullable.address,com.nest5.Nest5Client.Member.address.nullable.java.lang.String,com.nest5.Nest5Client.Member.address.nullable,member.address.nullable.com.nest5.Nest5Client.Member.address,member.address.nullable.address,member.address.nullable.java.lang.String,member.address.nullable,nullable.com.nest5.Nest5Client.Member.address,nullable.address,nullable.java.lang.String,nullable]; arguments [address,class com.nest5.Nest5Client.Member]; default message [La propiedad [{0}] no puede ser nula]

	at BootStrap$_closure1.doCall(BootStrap.groovy:41)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
	at grails.util.Environment.executeForEnvironment(Environment.java:301)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
